[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "FacilityMeltdown"
description = "Maybe taking the apparatus out isn't such a great idea..."
websiteUrl = "https://github.com/LoafOrc/FacilityMeltdown"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.13.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/FacilityMeltdown.dll"
target = "./plugins/FacilityMeltdown/FacilityMeltdown.dll"

[[build.copy]]
source = "./bin/Release/facilitymeltdown"
target = "./plugins/FacilityMeltdown/facilitymeltdown"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = [ "riskofrain2", ]
[publish.categories]
riskofrain2 = [ "items", "skills", ]


